name: condax
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - click
  - requests
  - userpath
  - pyyaml
  # Test dependencies
  - pytest
  - coverage
  # Doc depe
  - rainbowlog >=2.0.0
  - types-PyYAML
  - types-requests